### ISSUE TITLE
Configurable log levels

### ISSUE THREAD

**Issue by kbrueckner** [munichbughunter/SevenFacette#168]
**Summary**
A proper logging based on different log levels would be desirable.
Possible log levels are as usual: none (default), info, debug, error

**Motivation**
Currently sevenfacette logs a lot of messages which I would not want to see unless I actively would set the log level accordingly. This can be disturbing.

**Comment by MaxRuenz** [comment]
We have also seen this today.
E.g. in the following files information is printed out to the console instead of using a logger:

- https://github.com/munichbughunter/SevenFacette/blob/b37add36823da426a21c0b74b1da815f62f7b53c/core/src/jvmMain/kotlin/de/p7s1/qa/sevenfacette/http/GenericHttpClient.kt#L270
- https://github.com/munichbughunter/SevenFacette/blob/ceb418aa667c409251351196a484c78a248eaa9d/core/src/commonMain/kotlin/de/p7s1/qa/sevenfacette/http/Url.kt#L95

These statements do print out sensitive information in our case, and we need a mechanism to hide them.
